name: Add Update Comment
on:
  issues:
    types:
      - labeled
jobs:
  update-comment:
    if: "${{ github.event.label.name == 'Feature: Feature Branch' }}"
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Find-Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: 1
          body-includes: Overview
    - name: Update-comment
        needs: Find-Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            Test 1
          reactions: eyes
          
    
