name: Add Feature Branch Comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: "${{ github.event.label.name == 'Feature: Feature Branch' }}"
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
     - name: Find Comment
       uses: peter-evans/find-comment@v1
       id: fc
       with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: REPLACE THIS TEXT 
     - name: Check outputs
       run: |
          echo "Comment ID - ${{ steps.fc.outputs.comment-id }}"
     - name: Update comment
       run: |
        await octokit.request('PATCH /repos/Zak234/website/issues/comments/${{ steps.fc.outputs.comment-id }}', {
        owner: 'Zak234',
        repo: 'website',
        comment_id: ${{ steps.fc.outputs.comment-id }},
        body: 'body'
        })
