name: Add Feature Branch Comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: "${{ github.event.label.name == 'Feature: Feature Branch' }}"
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
     - name: Find Comment
       uses: peter-evans/find-comment@v1
       id: fc
       with:
          issue-number: 1
          body-includes: 'Overview'
     - name: Update comment
       uses: peter-evans/create-or-update-comment@v1
       with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.issue.number }}
        body: |
         0123456789
         ${{github.event}}
 
