# This is a basic workflow to help you get started with Actions

name: Github-Action-Logging-System

# Controls when the workflow will run

on: 
    workflow_run:
        workflows:
            -Testing

jobs:
    build:
        runs-on: ubuntu-latest

    steps:
     - name: npm install, build, and test
     - uses: actions/checkout@v2
       run: |
          npm install
          npm run build --if-present
          npm test
 
     - name: Log artifact
     - uses: actions/upload-artifact@v2
       with:
          name: GitHub-logs
          path: github-logs.txt
