# This is a basic workflow to help you get started with Actions

name: Github-Action-Logging-System

# Controls when the workflow will run

on: 
workflow_run:
    workflows:
        -Testing

jobs:
build:
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v2
  - name: Uploads-Github-Logs
    uses: actions/upload-artifact@v2
    with:
          name: GitHub-logs
          path: github-logs.txt
